In [3]:
import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
import matplotlib.image as mpimg

In [4]:
import cv2 
import os 
import glob 
img_dir = r"C:\Users\Umar\image1" # Enter Directory of all images  
data_path = os.path.join(img_dir,'*g') 
files = glob.glob(data_path) 
data = [] 
for f1 in files: 
    img = cv2.imread(f1) 
    img.resize((200,200))
    data.append(img) 

In [5]:
import cv2 
import os 
import glob 
img_dirs = r"C:\Users\Umar\image22" # Enter Directory of all images  
data_paths = os.path.join(img_dirs,'*g') 
filess = glob.glob(data_paths) 
data1 = [] 
for f1 in filess: 
    imgs = cv2.imread(f1) 
    imgs.resize((200,200))
    data1.append(imgs) 

In [6]:
data

[array([[ 57,  57,  57, ...,  67,  61,  58],
        [ 67,  61,  58, ...,  61,  70,  64],
        [ 61,  70,  64, ...,  62,  60,  66],
        ...,
        [ 68,  77,  71, ...,  76,  74,  80],
        [ 76,  75,  79, ..., 168,  67,  98],
        [151,  48,  74, ...,  71,  77,  73]], dtype=uint8),
 array([[  0,   2,  29, ..., 245, 112, 231],
        [255,  85, 222, ...,   6,  31,   1],
        [  6,  31,   2, ...,   8,   5,  27],
        ...,
        [ 35,  70,  19, ...,  31,  45,  63],
        [ 30,  44,  63, ...,  82,  34,  56],
        [ 81,  27,  54, ..., 178, 231, 133]], dtype=uint8),
 array([[ 12,  45,  30, ..., 114,  72, 104],
        [127,  79, 109, ..., 167, 136, 168],
        [151, 124, 191, ...,  63, 133, 103],
        ...,
        [ 18,  16,  35, ..., 235, 238, 253],
        [236, 239, 254, ...,  95,  49, 121],
        [ 98,  49, 123, ...,  77,  53,  51]], dtype=uint8),
 array([[253, 253, 253, ...,  38,  40,  34],
        [ 35,  22,  16, ...,  44,  65,  98],
        [ 83, 10

In [7]:
data1

[array([[110,  70, 206, ..., 117, 154,  87],
        [ 90, 133,  68, ..., 121, 166,  99],
        [111, 153,  76, ..., 108,  78, 231],
        ...,
        [ 76, 237, 121, ...,   8,  15,  42],
        [ 95, 105, 145, ...,  86,  99,  77],
        [105, 114,  92, ...,  69, 231, 113]], dtype=uint8),
 array([[255, 246, 242, ..., 230, 250, 246],
        [228, 244, 244, ..., 179, 166, 165],
        [172, 159, 173, ..., 212, 212, 206],
        ...,
        [141, 140, 153, ..., 118, 149, 182],
        [150, 182, 218, ..., 201,  95, 190],
        [205,  95, 189, ...,  90,  99,  30]], dtype=uint8),
 array([[172, 218, 235, ..., 231, 159, 216],
        [231, 157, 216, ..., 203, 205, 199],
        [198, 200, 201, ..., 213, 112,   4],
        ...,
        [232, 236, 229, ..., 252, 205, 183],
        [252, 205, 178, ..., 203,  18, 118],
        [182,  30, 123, ...,  55,  79, 106]], dtype=uint8),
 array([[172, 218, 235, ..., 231, 159, 216],
        [231, 157, 216, ..., 203, 205, 199],
        [198, 20

In [8]:
x=data+data1

In [9]:
x=np.array(x)
x

array([[[ 57,  57,  57, ...,  67,  61,  58],
        [ 67,  61,  58, ...,  61,  70,  64],
        [ 61,  70,  64, ...,  62,  60,  66],
        ...,
        [ 68,  77,  71, ...,  76,  74,  80],
        [ 76,  75,  79, ..., 168,  67,  98],
        [151,  48,  74, ...,  71,  77,  73]],

       [[  0,   2,  29, ..., 245, 112, 231],
        [255,  85, 222, ...,   6,  31,   1],
        [  6,  31,   2, ...,   8,   5,  27],
        ...,
        [ 35,  70,  19, ...,  31,  45,  63],
        [ 30,  44,  63, ...,  82,  34,  56],
        [ 81,  27,  54, ..., 178, 231, 133]],

       [[ 12,  45,  30, ..., 114,  72, 104],
        [127,  79, 109, ..., 167, 136, 168],
        [151, 124, 191, ...,  63, 133, 103],
        ...,
        [ 18,  16,  35, ..., 235, 238, 253],
        [236, 239, 254, ...,  95,  49, 121],
        [ 98,  49, 123, ...,  77,  53,  51]],

       ...,

       [[172, 218, 235, ..., 231, 159, 216],
        [231, 157, 216, ..., 203, 205, 199],
        [198, 200, 201, ..., 213, 112,   4

In [10]:
x.shape

(25, 200, 200)

In [11]:
x=x.reshape(25, 200* 200)
x

array([[ 57,  57,  57, ...,  71,  77,  73],
       [  0,   2,  29, ..., 178, 231, 133],
       [ 12,  45,  30, ...,  77,  53,  51],
       ...,
       [172, 218, 235, ...,  55,  79, 106],
       [172, 218, 235, ...,  55,  79, 106],
       [ 56,  63,  88, ..., 121, 150,  69]], dtype=uint8)

In [12]:
x.shape

(25, 40000)

In [13]:
o=np.ones([20])
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [14]:
z=np.zeros([5])
z

array([0., 0., 0., 0., 0.])

In [15]:
y=np.append(o,z)
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 0.])

In [16]:
y.shape

(25,)

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,shuffle=True,random_state=150)

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
linear=LogisticRegression()

In [21]:
linear.fit(xtrain,ytrain)

LogisticRegression()

In [22]:
linear.predict(xtest)

array([0., 1., 1., 1., 0.])

In [23]:
linear.score(xtest,ytest)

0.8

In [24]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
DTC= DecisionTreeClassifier()

In [26]:
DTC.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [27]:
DTC.predict(xtest)

array([0., 1., 1., 1., 1.])

In [28]:
DTC.score(xtest,ytest)

1.0

In [29]:
from sklearn.svm import SVC

In [30]:
support=SVC(kernel="linear")

In [31]:
support.fit(xtrain,ytrain)

SVC(kernel='linear')

In [32]:
support.predict(xtest)

array([0., 1., 1., 1., 0.])

In [33]:
support.score(xtest,ytest)

0.8

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
random=RandomForestClassifier()

In [36]:
random.fit(xtrain,ytrain)

RandomForestClassifier()

In [37]:
random.predict(xtest)

array([0., 1., 1., 1., 1.])

In [38]:
random.score(xtest,ytest)

1.0

In [39]:
from sklearn.neighbors import KNeighborsClassifier

In [40]:
KNN=KNeighborsClassifier()

In [41]:
KNN.fit(xtrain,ytrain)

KNeighborsClassifier()

In [42]:
KNN.predict(xtest)

array([1., 1., 1., 1., 1.])

In [43]:
KNN.score(xtest,ytest)

0.8

In [44]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report

In [45]:


accuracy_score(ytest,linear.predict(xtest))


0.8

In [46]:
recall_score(ytest,linear.predict(xtest))

0.75

In [47]:
f1_score(ytest,linear.predict(xtest))

0.8571428571428571

In [48]:
accuracy_score(ytest,DTC.predict(xtest))

1.0

In [49]:
recall_score(ytest,DTC.predict(xtest))

1.0

In [50]:
f1_score(ytest,DTC.predict(xtest))

1.0

In [51]:
accuracy_score(ytest,random.predict(xtest))

1.0

In [52]:
recall_score(ytest,random.predict(xtest))

1.0

In [53]:
f1_score(ytest,random.predict(xtest))

1.0

In [54]:
accuracy_score(ytest,support.predict(xtest))

0.8

In [55]:
recall_score(ytest,support.predict(xtest))

0.75

In [56]:
f1_score(ytest,support.predict(xtest))

0.8571428571428571

In [57]:
accuracy_score(ytest,KNN.predict(xtest))

0.8

In [58]:
recall_score(ytest,KNN.predict(xtest))

1.0

In [59]:
f1_score(ytest,KNN.predict(xtest))

0.888888888888889

In [60]:
R={
    
    
    "Logistic_Regression":[linear.score(xtest,ytest)],
    "Decision_Tree_classifier":[DTC.score(xtest,ytest)],
    "Support_vector_Mechine":[support.score(xtest,ytest)],
    "Random_Forest_Classifier":[random.score(xtest,ytest)],
    "KNeighbors_Classifier":[KNN.score(xtest,ytest)]
}

In [61]:
d=pd.DataFrame(R).T
d


0
Logistic_Regression       0.8
Decision_Tree_classifier  1.0
Support_vector_Mechine    0.8
Random_Forest_Classifier  1.0
KNeighbors_Classifier     0.8

In [62]:
d["Accuracy_score"]=[accuracy_score(ytest,linear.predict(xtest)),accuracy_score(ytest,DTC.predict(xtest)),accuracy_score(ytest,support.predict(xtest)),accuracy_score(ytest,random.predict(xtest)),accuracy_score(ytest,KNN.predict(xtest))]

In [63]:
d["F1_score"]=[f1_score(ytest,linear.predict(xtest)),f1_score(ytest,DTC.predict(xtest)),f1_score(ytest,support.predict(xtest)),f1_score(ytest,random.predict(xtest)),f1_score(ytest,KNN.predict(xtest))]

In [64]:
d["Recall_score"]=[recall_score(ytest,linear.predict(xtest)),recall_score(ytest,DTC.predict(xtest)),recall_score(ytest,support.predict(xtest)),recall_score(ytest,random.predict(xtest)),recall_score(ytest,KNN.predict(xtest))]

In [65]:
d

0  Accuracy_score  F1_score  Recall_score
Logistic_Regression       0.8             0.8  0.857143          0.75
Decision_Tree_classifier  1.0             1.0  1.000000          1.00
Support_vector_Mechine    0.8             0.8  0.857143          0.75
Random_Forest_Classifier  1.0             1.0  1.000000          1.00
KNeighbors_Classifier     0.8             0.8  0.888889          1.00

In [66]:
from sklearn.metrics import confusion_matrix

In [67]:
cm1 = confusion_matrix(ytest,linear.predict(xtest))
sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity1 )

Sensitivity :  1.0


In [68]:
cm1 = confusion_matrix(ytest,DTC.predict(xtest))
sensitivity2 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity2 )

Sensitivity :  1.0


In [69]:
cm1 = confusion_matrix(ytest,support.predict(xtest))
sensitivity3 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity3 )

Sensitivity :  1.0


In [70]:
cm1 = confusion_matrix(ytest,random.predict(xtest))
sensitivity4 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity4 )

Sensitivity :  1.0


In [71]:
cm1 = confusion_matrix(ytest,KNN.predict(xtest))
sensitivity5 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity5 )

Sensitivity :  0.0


In [72]:
d["Sensitivity_score"]=[sensitivity1,sensitivity2,sensitivity3,sensitivity4,sensitivity5]

In [73]:
d

0  Accuracy_score  F1_score  Recall_score  \
Logistic_Regression       0.8             0.8  0.857143          0.75   
Decision_Tree_classifier  1.0             1.0  1.000000          1.00   
Support_vector_Mechine    0.8             0.8  0.857143          0.75   
Random_Forest_Classifier  1.0             1.0  1.000000          1.00   
KNeighbors_Classifier     0.8             0.8  0.888889          1.00   

                          Sensitivity_score  
Logistic_Regression                     1.0  
Decision_Tree_classifier                1.0  
Support_vector_Mechine                  1.0  
Random_Forest_Classifier                1.0  
KNeighbors_Classifier                   0.0

In [74]:
cm1 = confusion_matrix(ytest,linear.predict(xtest))
specificity6 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity6)


Specificity :  0.75


In [75]:
cm1 = confusion_matrix(ytest,DTC.predict(xtest))
specificity7 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity7)

Specificity :  1.0


In [76]:
cm1 = confusion_matrix(ytest,support.predict(xtest))
specificity8 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity8)

Specificity :  0.75


In [77]:
cm1 = confusion_matrix(ytest,random.predict(xtest))
specificity9 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity9)

Specificity :  1.0


In [78]:
cm1 = confusion_matrix(ytest,KNN.predict(xtest))
specificity10= cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity10)

Specificity :  1.0


In [79]:
d["Specificity"]=[specificity6,specificity7,specificity8,specificity9,specificity10]

In [80]:
d=d.rename(columns={0:"Score"})
d

Score  Accuracy_score  F1_score  Recall_score  \
Logistic_Regression         0.8             0.8  0.857143          0.75   
Decision_Tree_classifier    1.0             1.0  1.000000          1.00   
Support_vector_Mechine      0.8             0.8  0.857143          0.75   
Random_Forest_Classifier    1.0             1.0  1.000000          1.00   
KNeighbors_Classifier       0.8             0.8  0.888889          1.00   

                          Sensitivity_score  Specificity  
Logistic_Regression                     1.0         0.75  
Decision_Tree_classifier                1.0         1.00  
Support_vector_Mechine                  1.0         0.75  
Random_Forest_Classifier                1.0         1.00  
KNeighbors_Classifier                   0.0         1.00